// Auto-generated by analysis/fit_tango_challenge_model.py — do not edit by hand.
// Drop-in P(challenge) function — mirrors Tango's structural model fit on MLB 2026 data.
//
// Usage:
//   const p = tangoChallengeProb({
//     side: 'offense' | 'defense',
//     plateX, plateZ, szTop, szBot,
//     balls, strikes,                 // POST-pitch count of the AS-CALLED pitch
//     outsRem, priorLost, basesCode,  // basesCode in '000'..'111'
//   });
//
// CONVENTIONS — pass these exactly or the lookup lands in the wrong cell:
//   side    : from the call AS THE UMPIRE MADE IT (a called strike is always
//             'offense'). Never derive it from a post-review call.
//   outsRem : outs left in the game for BOTH teams, 54-out scale (54 at first
//             pitch, ~6 per full inning, floor 1). Not 27.
//
import TANGO from './tango_chal_prob_2026.json';

const PLATE_HALF_FT = 17/24;
const BALL_RADIUS_FT = 1.45/12;   // strike/ball line is the BALL EDGE (see the
                                  // Python proximity_bucket docstring)
const BUCKET_THRESHOLD_IN = TANGO.feature_spec.bucket_threshold_in;

function _bucket(plateX, plateZ, szTop, szBot) {
  const xExcess = Math.abs(plateX) - (PLATE_HALF_FT + BALL_RADIUS_FT);
  const zHigh = plateZ - (szTop + BALL_RADIUS_FT);
  const zLow = (szBot - BALL_RADIUS_FT) - plateZ;
  const inside = xExcess < 0 && zHigh < 0 && zLow < 0;
  if (inside) {
    const inIn = -Math.min(xExcess, zHigh, zLow) * 12;
    return inIn > BUCKET_THRESHOLD_IN ? 'easy_strike' : 'close_strike';
  }
  const outIn = Math.sqrt(Math.max(0, xExcess) ** 2 + Math.max(0, zHigh, zLow) ** 2) * 12;
  return outIn > BUCKET_THRESHOLD_IN ? 'easy_ball' : 'close_ball';
}

function _outsBin(outsRem) {
  if (outsRem <= 3) return '1-3';
  if (outsRem <= 9) return '4-9';
  if (outsRem <= 18) return '10-18';
  return '19+';
}

export function tangoChallengeProb({ side, plateX, plateZ, szTop, szBot, balls, strikes, outsRem, priorLost, basesCode }) {
  const bucket = _bucket(plateX, plateZ, szTop, szBot);
  const outsBin = _outsBin(outsRem);
  const lost = Math.min(2, Math.max(0, priorLost | 0));

  // Each entry below is an (oneHotKey, condition) pair. The intercept covers the
  // reference levels (defense, easy_strike, balls=0, strikes=0, outs_bin=1-3,
  // prior_lost=0, bases=000), so we add a coef only when the level differs.
  const C = TANGO.coefs;
  let lo = TANGO.intercept;
  const add = (k) => { if (C[k] !== undefined) lo += C[k]; };

  add(`side_${side}`);
  add(`bucket_${bucket}`);
  add(`balls_${balls}`);
  add(`strikes_${strikes}`);
  add(`outs_bin_${outsBin}`);
  add(`prior_lost_${lost}`);
  add(`bases_${basesCode}`);
  add(`sidebucket_${side}__${bucket}`);
  add(`sidestr_${side}__s${strikes}`);
  add(`sideball_${side}__b${balls}`);

  return 1 / (1 + Math.exp(-lo));
}
